name: dependency-review

on:
  - pull_request_target

jobs:
  shared:
    uses: amezin/js-actions-common/.github/workflows/shared-dependency-review.yml@4383e5abf3fa3f1295a5f991a90427ce9af04ad1 # v2.1.0
    permissions:
      contents: read
      pull-requests: write
