name: dependency-review

on:
  - pull_request_target

jobs:
  shared:
    uses: amezin/js-actions-common/.github/workflows/shared-dependency-review.yml@961ae80497f79f886278f1d47b1d4bf70963b941 # v2.0.2
    permissions:
      contents: read
      pull-requests: write
