name: dependency-review

on:
  - pull_request_target

jobs:
  shared:
    uses: amezin/js-actions-common/.github/workflows/shared-dependency-review.yml@f41ef584a55c4b52a294a78c8e48f35e015e4b1a # v2.0.0
    permissions:
      contents: read
      pull-requests: write
