name: dependency-review

on:
  - pull_request_target

jobs:
  shared:
    uses: amezin/js-actions-common/.github/workflows/shared-dependency-review.yml@06c4924164b0f9e608fbb977b6d0331ebee42e3f # v5.0.0
    permissions:
      contents: read
      pull-requests: write
